---
variables:
  KANIKO_BUILD_ARGS: "--build-arg SNAPSHOT=20191129T030053Z  --destination docker.io/shadowhunt/base:20191129T030053Z --destination docker.io/shadowhunt/base:latest"
  
include:
    - remote: 'https://gitlab.shadowhunt.de/open-source/pipeline-templates/-/raw/master/environment/gitlab-ci-template.yml'
    - remote: 'https://gitlab.shadowhunt.de/open-source/pipeline-templates/-/raw/master/kaniko/gitlab-ci-template.yml'

stages:
    - prepare
    - build
    - deploy

